[theme]
base="dark"
primaryColor="#4FC3F7"
backgroundColor="#0F2027"
secondaryBackgroundColor="#203A43"
textColor="#E0F7FA"
font="sans serif"
st.markdown("""
    <style>
        .main {
            background-color: #0F2027;
        }
        h1, h2, h3 {
            color: #E0F7FA;
        }
    </style>
""", unsafe_allow_html=True)
st.image("https://images.unsplash.com/photo-1507525428034-b723cf961d3e")
st.title("💧 WATER QUALITY SYSTEM")
st.caption("Smart Monitoring & Prediction")
st.markdown("---")
